[package]
name = "writer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
redis = "0.21"
slint = "0.3.0"
slint-interpreter = { version = "0.3.0", features = ["display-diagnostics"] }
spin_on = "0.1.1"
