import { VerticalBox, LineEdit, Button, Slider } from "std-widgets.slint";


MainWindow := Window {
    // This is the "API for this writer application.
    // There is a family of callbacks to send data to redis, with name
    // (set|lpush|rpush)_(i32|f32|bool|string) and arguments (string, value).
    //
    // Commands can be set with the cmd(string, [string]) callback.

    // The callbacks that the UI can use to send data to redis.
    callback set_i32(string, int);
    // callback set_f32(string, float);
    // callback set_bool(string, bool);
    // callback set_string(string, string);
    callback rpush_i32(string, int);
    callback cmd(string, [string]);

    // With this, do whatever you want! :)

    // Whatever one wants
    property <int> counter: 0;

    VerticalBox {
        variable := LineEdit {
            placeholder-text: "Variable";
        }

        button := Button {
            text: "Press to bind to list " + variable.text;
            clicked => {
                counter += 1;
                root.cmd("rsp.bind", ["--list", variable.text]);
            }
        }

        Slider {
            minimum: -100;
            maximum: 100;
            value: 0;
            changed(x) => {
                root.rpush_i32(variable.text, x);
            }
        }
    }
}
